AWSTemplateFormatVersion: '2010-09-09'
Description: Infraestructura completa para AntHill (VPC, EC2 y S3)

Resources:
  # --- RED ---
  AntHillVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: AntHill-VPC

  AntHillIGW:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref AntHillVPC
      InternetGatewayId: !Ref AntHillIGW

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AntHillVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: AntHill-Public-Subnet

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref AntHillVPC

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref AntHillIGW

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # --- SEGURIDAD ---
  AntHillSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permite trafico HTTP y SSH (restringido)
      VpcId: !Ref AntHillVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5001
          ToPort: 5002
          CidrIp: 0.0.0.0/0 # Puertos de tus microservicios

  # --- ALMACENAMIENTO ---
  AntHillReportsBucket:
    Type: AWS::S3::Bucket
    Properties:
      # El nombre tiene que ser unico en el mundo
      BucketName: !Sub "anthill-reportes-${AWS::AccountId}" 
      VersioningConfiguration:
        Status: Enabled

  # --- COMPUTO ---
  AntHillServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      # AMI de Amazon Linux 2 us-east-1
      ImageId: ami-0c101f26f147fa7fd 
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref AntHillSecurityGroup
      # Usamos el perfil que ya viene en el lab
      IamInstanceProfile: LabInstanceProfile 
      Tags:
        - Key: Name
          Value: AntHill-Web-Server

  # --- BASE DE DATOS ---
  AntHillPostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "AntHill-Posts"
      AttributeDefinitions:
        - AttributeName: "PostId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PostId"
          KeyType: "HASH"
      # PAY_PER_REQUEST para no quemar presupuesto
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Name
          Value: AntHill-Posts-Table

Outputs:
  InstancePublicIP:
    Value: !GetAtt AntHillServer.PublicIp
  BucketName:
    Value: !Ref AntHillReportsBucket